// <auto-generated />
using System;
using BackOfficeAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BackOfficeAPI.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20220726162225_updateCandidature")]
    partial class updateCandidature
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BackOfficeAPI.Models.Candidature", b =>
                {
                    b.Property<int?>("OffreFK")
                        .HasColumnType("integer");

                    b.Property<int?>("CandidatFK")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DateCandidature")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Etat")
                        .HasColumnType("integer");

                    b.Property<int?>("PartinenceProfil")
                        .HasColumnType("integer");

                    b.Property<bool?>("ProfileInteressant")
                        .HasColumnType("boolean");

                    b.HasKey("OffreFK", "CandidatFK");

                    b.HasIndex("CandidatFK");

                    b.ToTable("Candidatures");
                });

            modelBuilder.Entity("BackOfficeAPI.Models.Offre", b =>
                {
                    b.Property<int?>("OffreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("OffreId"));

                    b.Property<int?>("AdminFK")
                        .HasColumnType("integer");

                    b.Property<string>("Adresse")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("Etat")
                        .HasColumnType("integer");

                    b.Property<int[]>("Proffesions")
                        .HasColumnType("integer[]");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("OffreId");

                    b.HasIndex("AdminFK");

                    b.ToTable("Offres");
                });

            modelBuilder.Entity("BackOfficeAPI.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("text");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nom")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("Prenom")
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool?>("Statut")
                        .HasColumnType("boolean");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("Discriminator").HasValue("User");
                });

            modelBuilder.Entity("BackOfficeAPI.Models.Admin", b =>
                {
                    b.HasBaseType("BackOfficeAPI.Models.User");

                    b.HasDiscriminator().HasValue("Admin");
                });

            modelBuilder.Entity("BackOfficeAPI.Models.Candidat", b =>
                {
                    b.HasBaseType("BackOfficeAPI.Models.User");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<int[]>("Proffesions")
                        .HasColumnType("integer[]");

                    b.Property<int?>("Telephone")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Candidat");
                });

            modelBuilder.Entity("BackOfficeAPI.Models.SuperAdmin", b =>
                {
                    b.HasBaseType("BackOfficeAPI.Models.User");

                    b.HasDiscriminator().HasValue("SuperAdmin");
                });

            modelBuilder.Entity("BackOfficeAPI.Models.Candidature", b =>
                {
                    b.HasOne("BackOfficeAPI.Models.Candidat", "Candidat")
                        .WithMany("Candidatures")
                        .HasForeignKey("CandidatFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackOfficeAPI.Models.Offre", "Offre")
                        .WithMany("Candidatures")
                        .HasForeignKey("OffreFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidat");

                    b.Navigation("Offre");
                });

            modelBuilder.Entity("BackOfficeAPI.Models.Offre", b =>
                {
                    b.HasOne("BackOfficeAPI.Models.Admin", "Admin")
                        .WithMany("Offres")
                        .HasForeignKey("AdminFK");

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("BackOfficeAPI.Models.Offre", b =>
                {
                    b.Navigation("Candidatures");
                });

            modelBuilder.Entity("BackOfficeAPI.Models.Admin", b =>
                {
                    b.Navigation("Offres");
                });

            modelBuilder.Entity("BackOfficeAPI.Models.Candidat", b =>
                {
                    b.Navigation("Candidatures");
                });
#pragma warning restore 612, 618
        }
    }
}
